---
- src: https://github.com/fdupont-redhat/ims.manageiq_vm_snapshot.git
  version: master
  name: ims.manageiq_vm_snapshot
- src: https://github.com/fdupont-redhat/ims.postmigration-convert2rhel.git
  version: summit_2020
  name: ims.postmigration-convert2rhel
- src: https://github.com/fdupont-redhat/ims.postmigration-leapp.git
  version: master
  name: ims.postmigration-leapp
- src: https://github.com/fdupont-redhat/ims.premigration-force_nic_names.git
  version: master
  name: ims.premigration-force_nic_names
